import cv2
import numpy as np
img=cv2.imread("opencv/images.jpg",cv2.IMREAD_GRAYSCALE)
edges=cv2.Canny(img,50,150)
ret,thresh_img=cv2.threshold(img,180,255,cv2.THRESH_BINARY)
inp=input("Enter which image processing do you want canny or thresh")
if inp=="canny":
    cv2.imshow("original image",img)
    cv2.imshow("Edges",edges)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
elif inp=="thresh":
    cv2.imshow("thresh image",thresh_img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    img1=np.zeros((300,300),dtype="uint8")
    img2=np.zeros((300,300),dtype="uint8")
    cv2.circle(img1,(150,150),100,255,-1)
    cv2.rectangle(img2,(100,100),(250,250),255,-1)
    bitwise_and=cv2.bitwise_and(img1,img2)
    bitwise_or=cv2.bitwise_or(img1,img2)
    bitwise_not=cv2.bitwise_not(img1)
    cv2.imshow("circle",img1)
    cv2.imshow('rectangle',img2)
    cv2.imshow("AND",bitwise_and)
    cv2.imshow("OR",bitwise_or)
    cv2.imshow("NOT",bitwise_not)
    cv2.waitKey(0)
    cv2.destroyAllWindows()